Clean whitespaces

diff --git a/ddig b/ddig
--- a/ddig
+++ b/ddig
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (C) 2013 Jonas Friedmann under the "Do What The Fuck You Want To Public" License 
+# Copyright (C) 2013 Jonas Friedmann under the "Do What The Fuck You Want To Public" License
 # (see ./LICENSE for more informations)
 
 #####
@@ -15,11 +15,11 @@ i=1
 
 # Usage function
 usage(){
-	echo "Usage: ${0} <hostname>"
-	echo ""
-	echo "options:"
-    echo "-h 	show this help"
-	exit 1
+  echo "Usage: ${0} <hostname>"
+  echo ""
+  echo "options:"
+    echo "-h  show this help"
+  exit 1
 }
 
 # Get all passed arguments
@@ -36,8 +36,8 @@ shift $((OPTIND-1))
 # Check if argument is given
 if [ -z "${hostname}" ]
 then
-	echo "Error: no argument given!"
-	usage
+  echo "Error: no argument given!"
+  usage
 fi
 
 # Find responsible DNS
@@ -46,21 +46,21 @@ dns=$(dig ns +short ${hostname})
 # Check for empty response
 if [ -z "${dns}" ]
 then
-	echo "Error: Couldn't resolve hostname!"
-	exit 1
+  echo "Error: Couldn't resolve hostname!"
+  exit 1
 fi
 
-# For each resulted server 
+# For each resulted server
 for server in ${dns}
 do
-	echo "$i. responsible DNS:   ${server}"
-    
+  echo "$i. responsible DNS:   ${server}"
+
     # Lookup PTR
     direct=$(dig ${hostname} +short @${server})
-	
+
     echo "   resolved hostname: ${direct}"
 
-	# Count
-	i=$((i+1))
+  # Count
+  i=$((i+1))
 done
 exit 0
